# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Check build sanity
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Print diff
      run: git diff
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Send email
      if: job.status == 'failure'
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.GMAIL_SMTP_USER}}
        password: ${{secrets.GMAIL_SMTP_PASS}}
        subject: Github Actions job result
        body: Build job of ${{github.repository}} completed successfully!
        to: gavinharris123@gmail.com
        from: Github Actions # <no-reply@gmail.com>
        content_type: text/html
